[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info

[INPUT]
    Name              tail
    Path              /var/log/dlt/dlt-structured.jsonl
    Parser            json
    Tag               dlt.ecu
    Refresh_Interval  1
    Mem_Buf_Limit     64MB

[FILTER]
    Name              record_modifier
    Match             dlt.ecu
    Record            source dlt-daemon
    Record            protocol autosar_dlt

[OUTPUT]
    Name              forward
    Match             dlt.ecu
    Host              127.0.0.1
    Port              24224
