foreground = no
debug = notice
pid = /run/stunnel-dlt-forwarder.pid

[dlt_forward]
client = yes
accept = 127.0.0.1:13490
connect = logs.myco.internal:443
CAfile = /etc/dlt/tls/ca.crt
cert = /etc/dlt/tls/client.crt
key = /etc/dlt/tls/client.key
verifyChain = yes
